### ISSUE TITLE
Sammensetning av sider feil

### ISSUE THREAD

**Issue by kriswdue** [Lanjelin/NBNO.py#14]
Hei!

Sidene som settes sammen blir ikke korrekte... se vedlagte eksempler. Har forsøkr forskjellige bøker, og jeg får i alle fall samme resultat. Kjører det via på WSL/Ubuntu i et venv med Python 3.10.12

![0003](https://github.com/Lanjelin/NBNO.py/assets/37191151/b989ccbe-e1fd-4873-9b1f-67733a8ef7fe)
![0005](https://github.com/Lanjelin/NBNO.py/assets/37191151/4a49f2e7-2795-47aa-943c-df8058fcd295)

**Comment by Lanjelin** [comment]
Ikke greid å provosere dette, kjørt koden på flere forskjellige systemer, men har ikke mulighet for å teste på WSL.
Merger fiksen din allikevel, da det gir mening.
