### ISSUE TITLE
SSL-feilmelding

### ISSUE THREAD

**Issue by Hawk-on** [Lanjelin/NBNO.py#8]
Endra fra HTTPAdapter til SSLAdapter etter å ha fått feilmelding gjentatte ganger.
`from requests_toolbelt import SSLAdapter`
`self.adapter = SSLAdapter(ssl.PROTOCOL_TLSv1_2)
`

**Comment by Lanjelin** [comment]
Litt tregt svar fra min side.  
Har kikket litt på denne et par ganger uten å klare å reprodusere noen feil.  
En eventuell feilmelding kunne gitt litt mer pekepin.
Velger å lukke denne intill videre.
